export { default as Jumbotron } from "./Jumbotron/Jumbotron";
export { default as Footer } from "./Footer/Footer";
export { default as Navbar } from "./Navbar/Navbar";
export { default as Home } from "./Home/Home";
export { default as Post } from "./Post/Post";
export { default as Pagination } from "./Pagination/Pagination";
export { default as Categories } from "./Categories/Categories";
export { default as Photo } from "./Photo/Photo";
export { default as RelatedPhotos } from "./RelatedPhotos/RelatedPhotos";